[package]
name = "walkers_extras"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "extra functionalities for walkers crate"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
egui.workspace = true
geo.workspace = true
geojson.workspace = true
kml.workspace = true
log.workspace = true
lyon_path.workspace = true
lyon_tessellation.workspace = true
quick-xml.workspace = true
rstar.workspace = true
thiserror.workspace = true
walkers = { workspace = true, features = ["mvt"] }
