[package]
name = "walkers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "slippy map widget for egui"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytes.workspace = true
color = { workspace = true, optional = true }
egui.workspace = true
egui_extras.workspace = true
futures.workspace = true
geo = { workspace = true, optional = true }
geo-types.workspace = true
image = { workspace = true, features = ["jpeg", "png"] }
log.workspace = true
lru.workspace = true
lyon_path = { workspace = true, optional = true }
lyon_tessellation = { workspace = true, optional = true }
mvt-reader = { workspace = true, optional = true }
pmtiles = { workspace = true, optional = true }
reqwest.workspace = true
reqwest-middleware.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
eframe.workspace = true
env_logger.workspace = true
hypermocker = { path = "../hypermocker" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
http-cache-reqwest.workspace = true
tokio.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-futures.workspace = true

[features]
default = []
mvt = [
  "dep:color",
  "dep:geo",
  "dep:lyon_path",
  "dep:lyon_tessellation",
  "dep:mvt-reader",
  "dep:serde",
  "dep:serde_json"
]
pmtiles = ["dep:pmtiles"]
serde = ["dep:serde", "egui/serde", "geo-types/serde"]
