[package]
name = "demo_android"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
log.workspace = true
android_logger.workspace = true
eframe = { workspace = true, features = ["wgpu", "android-game-activity"] }
egui-winit.workspace = true
demo = { path = "../../demo" }

[lib]
name = "main"
crate-type = ["cdylib"]
