help:
    @just --list --unsorted

# Pass `--release` for a build worth judging performance by. A debug wasm build is far slower.
build *args:
    trunk build {{ args }}

serve *args:
    trunk serve {{ args }}
