[package]
name = "hypermocker"
edition.workspace = true
version = "0.1.0"
publish = false

[dependencies]
hyper.workspace = true
tokio = { workspace = true, features = ["macros"] }
hyper-util.workspace = true
http-body-util.workspace = true
log.workspace = true

[dev-dependencies]
reqwest.workspace = true
futures.workspace = true
env_logger.workspace = true
tokio-test.workspace = true
