[package]
name = "wanderers"
description = "Journal of the places you have been to, and the ones you still want to see."
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
walkers.workspace = true
eframe.workspace = true
egui.workspace = true
env_logger.workspace = true
